Web Dev Assignment 1/Controllers/DiscussionForumsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Web_Dev_Assignment_1.Data;
using Web_Dev_Assignment_1.Models;

namespace Web_Dev_Assignment_1.Controllers
{
    public class DiscussionForumsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DiscussionForumsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: DiscussionForums
        public async Task<IActionResult> Index()
        {
            return View(await _context.DiscussionForum.ToListAsync());
        }

        // GET: DiscussionForums/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var discussionForum = await _context.DiscussionForum
                .FirstOrDefaultAsync(m => m.Id == id);
            if (discussionForum == null)
            {
                return NotFound();
            }

            return View(discussionForum);
        }

        // GET: DiscussionForums/Create
        [Authorize(Roles = "Manager, RegisteredUser")]
        public IActionResult Create()
        {
            DiscussionForum df = new DiscussionForum();
            df.PostDate = DateTime.Now;
            df.UserName = User.Identity.Name;
            return View(df);
        }

        // POST: DiscussionForums/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Manager, RegisteredUser")]
        public async Task<IActionResult> Create([Bind("Id,PostDate,UserName,Heading,Rating,TopicTitle,MessageContent,Like,Dislike")] DiscussionForum discussionForum)
        {
            if (ModelState.IsValid)
            {
                _context.Add(discussionForum);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(discussionForum);
        }

        // GET: DiscussionForums/Edit/5
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var discussionForum = await _context.DiscussionForum.FindAsync(id);
            if (discussionForum == null)
            {
                return NotFound();
            }
            return View(discussionForum);
        }

        // POST: DiscussionForums/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PostDate,UserName,Heading,Rating,TopicTitle,MessageContent,Like,Dislike")] DiscussionForum discussionForum)
        {
            if (id != discussionForum.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(discussionForum);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DiscussionForumExists(discussionForum.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(discussionForum);
        }

        // GET: DiscussionForums/Delete/5
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var discussionForum = await _context.DiscussionForum
                .FirstOrDefaultAsync(m => m.Id == id);
            if (discussionForum == null)
            {
                return NotFound();
            }

            return View(discussionForum);
        }

        // POST: DiscussionForums/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var discussionForum = await _context.DiscussionForum.FindAsync(id);
            _context.DiscussionForum.Remove(discussionForum);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DiscussionForumExists(int id)
        {
            return _context.DiscussionForum.Any(e => e.Id == id);
        }

        public async Task<IActionResult> IncreaseLike(int? id)
        {
            if (id == null) { return NotFound(); }
            var discussionForum = await _context.DiscussionForum.FindAsync(id); if (discussionForum == null) { return NotFound(); }
            if (ModelState.IsValid)
            {
                try
                {
                    if (User.Identity.IsAuthenticated && discussionForum.canIncreaseLike)
                    {
                        discussionForum.Like++; discussionForum.canIncreaseLike = false;
                        _context.Update(discussionForum);
                        await _context.SaveChangesAsync();
                    }
                }

                catch (DbUpdateConcurrencyException)
                {
                    if (!DiscussionForumExists(discussionForum.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Companies", "Home");
            }
            return RedirectToAction("Companies", "Home");
        }
        public async Task<IActionResult> IncreaseDislike(int? id)
        {
            if (id == null) { return NotFound(); }
            var discussionForum = await _context.DiscussionForum.FindAsync(id); if (discussionForum == null) { return NotFound(); }
            if (ModelState.IsValid)
            {
                try
                {
                    if (User.Identity.IsAuthenticated && discussionForum.canIncreaseDislike)
                    {
                        discussionForum.Dislike++; discussionForum.canIncreaseDislike = false;
                        _context.Update(discussionForum);
                        await _context.SaveChangesAsync();
                    }
                }

                catch (DbUpdateConcurrencyException)
                {
                    if (!DiscussionForumExists(discussionForum.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Companies", "Home");
            }
            return RedirectToAction("Companies", "Home");

        }

    }
}

Web Dev Assignment 1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Web_Dev_Assignment_1.Models;
using Web_Dev_Assignment_1.Data;
using Microsoft.EntityFrameworkCore;

namespace Web_Dev_Assignment_1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Companies() 
        {
            /* return View(await _context.DiscussionForum.ToListAsync()); */
            if (!User.Identity.IsAuthenticated)
            {
                foreach (var post in _context.DiscussionForum)
                {
                    post.canIncreaseLike = true;
                    post.canIncreaseDislike = true;
                }
                await _context.SaveChangesAsync();
            }

            var allDiscussions = from result in _context.DiscussionForum 
                                 orderby result.PostDate descending 
                                 select result;
            return View(await allDiscussions.ToListAsync());
        }

        public IActionResult Technologies()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Web Dev Assignment 1/Views/Home/Companies.cshtml

@{
    ViewData["Title"] = "Companies & Organisations";
}

<div class="container-fluid px-0">
    <article>
        <section id="bg3" class="col-md-12 col-sm-12 col-12">
            <header id="ind">Companies and Organisations</header> <!--Large Header-->
            <p id="intro">
                The Industry 4.0 market is forecasted to reach $1 trillion by 2030, dominated by global technology giants including Alphabet-Google, HP, Samsung, IBM, NEC, Microsoft, and more.
                According to the new 4-volume report by HSRC: Global Industry 4.0 Market & Technologies 2018-2023, the Industry 4.0 market will reach $214B by 2023
                <br /> <a href="https://www.prnewswire.com/news-releases/global-tech-giants-to-lead-the-industry-40-revolution-300585640.html">www.prnews.com</a>
            </p>
        </section>

        <section id="tech" class="row no-gutters">
            <div id="company1" class="container col-md-6 col-sm-6 col-12">
                <div id="textcompany1" class="centered hidden">
                    <h2 id="boothead"> IBM</h2>
                    <a href="https://www.ibm.com/industries/manufacturing" class="btn btn-primary">Visit Website</a>
                </div>
                <img src="~/images/Companies/ibm.jpg" class="img-fluid w-100">
            </div>
            <div id="company2" class="col-md-6 col-sm-6 col-12">
                <div id="textcompany2" class="centered  hidden">
                    <h1 id="boothead">Amazon</h1>
                    <a href="https://aws.amazon.com/ai/" class="btn btn-primary">Visit Website</a>
                </div>
                <img src="~/images/Companies/amazon.jpg" class="img-fluid w-100">
            </div>
            <div id="company3" class="col-md-12 col-sm-12 col-12">
                <div id="textcompany3" class="centered  hidden">
                    <h1 id="boothead">Amazon</h1>
                    <a href="https://aws.amazon.com/ai/" class="btn btn-primary">Visit Website</a>
                </div>
                <img src="~/images/Companies/google.jpg" class="img-fluid w-100">
            </div>
            <div id="company4" class="col-md-6 col-sm-6 col-12">
                <div id="textcompany4" class="centered  hidden">
                    <h1 id="boothead">Amazon</h1>
                    <a href="https://aws.amazon.com/ai/" class="btn btn-primary">Visit Website</a>
                </div>
                <img src="~/images/Companies/microsoft.jpg" class="img-fluid w-100">
            </div>
            <div id="company5" class="col-md-6 col-sm-6 col-12">
                <div id="textcompany5" class="centered  hidden">
                    <h1 id="boothead">CSIRO</h1>
                    <a href="https://www.csiro.au/" class="btn btn-primary">Visit Website</a>
                </div>
                <img src="~/images/Companies/CSIRO.jpg" class="img-fluid w-100">
            </div>

            <div id="company6" class="col-md-12 col-sm-12 col-12">
                <div id="textcompany6"class="centered hidden">
                    <h1 id="boothead">Department of Industry, Science, Energy and Resources</h1>
                    <a href="https://www.industry.gov.au/" class="btn btn-primary">Visit Website</a>
                </div>
                <img src="~/images/Companies/department.jpg" class="img-fluid w-100">
            </div>
        </section>
        <hr />
    </article>
    <div>
        @model IEnumerable<Web_Dev_Assignment_1.Models.DiscussionForum>

        <h1 id="feedback">Feedback</h1>

        @if (!User.Identity.IsAuthenticated)
        {
            <div style="text-align:center;">
                Please <a href="~/Identity/Account/Login">login</a> or <a href="~/Identity/Account/Register?returnUrl=~/Account/Register">create an account</a>
                to post your discussion on this page
            </div>
        }
        else
        {
            <div style="text-align:center;">
                <a href="~/DiscussionForums/Create/" class="btn btn-primary">Submit your feedback</a>
            </div>
        }

        @foreach (var item in Model)
        {
            <h2>@Html.DisplayFor(modelItem => item.TopicTitle)</h2>
            <p>
                @{ for (int i = 0; i < item.Rating; i++)
                    { <span style="color: #f8bd08; ">&#x2605;</span> }
                    for (int i = 0; i < 5 - item.Rating; i++)
                    { <span>&#x2606;</span> } }
            </p>
            <p>
                @Html.DisplayFor(modelItem => item.MessageContent)
            </p>
            <p> Posted by <b>@Html.DisplayFor(modelItem => item.UserName)</b> on @Html.DisplayFor(modelItem => item.PostDate)</p>
            <a asp-controller="DiscussionForums" asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-dark">Details</a>
            <a asp-controller="DiscussionForums" asp-action="IncreaseLike" asp-route-id="@item.Id" class="btn btn-success">Like</a>
            <a asp-controller="DiscussionForums" asp-action="IncreaseDislike" asp-route-id="@item.Id" class="btn btn-danger">Dislike</a>
            <a asp-controller="DiscussionForums" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-dark">Edit</a>
            <a asp-controller="DiscussionForums" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-dark">Delete</a>
            <hr />
        }
    </div>
</div>

Web Dev Assignment 1/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact & About";
}

<div>
        <div id="bg3" class="col-md-12 col-sm-12 col-12"">
            <div  class="centered">
                <header id="ind">Contact</header>
                <p id="endtext">This is the page for the contact information of this website</p>
            </div>
        </div>

        <div id="endtext" class="col-md-12centered col-sm-12 col-12">
            Phone Number:0468 548 969 <br/>
            Emailed: WDPAssignment@gmail.com<br />
            Student No:u3173658<br />
            Name: Ayden Smith<br />

        </div>
</div>

Web Dev Assignment 1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Homepage - Industry 4.0";
}

<body>
    <div class="container-fluid px-0">
        <!-- Full width Layout-->

        <article>
            <!--For search providers (Google/Bing)-->
            <section id="bg1" class="col-md-12 col-sm-12 col-12">
                <h1 id="ind">Industry 4.0</h1> <!--Large Header-->
                <p id="intro">
                    Industry 4.0 is a name given to the current trend of automation and data
                    exchange in manufacturing technologies. It includes cyber-physical systems, the Internet
                    cloud computing and cognitive computing. Industry 4.0 is commonly refferred to as the fourt industrial revolution. <br />Wikipedia
                </p>
            </section>

            <section class="row no-gutters">

                <div id="tech1" class="container col-lg-4 col-md-6 col-sm-6 col-12">
                    <div id="text" class="centered hidden">
                        <h4 id="boothead">Artificial Intelligence</h4>
                        <p>
                            Artificial intelligence (AI) is intelligence demonstrated by machines, as opposed to the natural intelligence displayed by humans or animals.
                            Leading AI textbooks define the field as the study of "intelligent agents": any system that perceives its environment and takes actions that maximize its chance of achieving its goals (Wikipedia).</
                        </p>
                    </div>
                    <img src="~/images/Homepage/ai.jpg" class="img-fluid">
                </div>

                <div id="tech2" class="container col-lg-4 col-md-6 col-sm-6 col-12">
                    <div id="text2" class="centered hidden">
                        <h4 id="boothead">Internet of Things</h4>
                        <p>
                            The Internet of things (IoT) describes the network of physical objects, so known as, "things"
                            — that are embedded with sensors, software, and other technologies that is used for the purpose of connecting
                            and exchanging data with other devices and systems over the Internet (Wikipedia).
                        </p>
                    </div>
                    <img src="~/images/Homepage/iot.jpg" class="img-fluid">
                </div>

                <div id="tech3" class="container col-lg-4 col-md-6 col-sm-6 col-12">
                    <div id="text3" class="centered hidden">
                        <h4 id="boothead">Cognitive Computing</h4>
                        <p>
                            Cognitive computing (CC) refers to technology platforms that, broadly speaking, are based on the scientific disciplines of artificial intelligence and signal processing.
                            These platforms encompass machine learning, reasoning, natural language processing, speech recognition and vision (object recognition),
                            human–computer interaction, dialog and narrative generation, among other technologies (Wikipedia).
                        </p>
                    </div>
                    <img src="~/images/Homepage/cognitive.jpg" class="img-fluid">
                </div>

                <div id="tech4" class="container col-lg-4 col-md-6 col-sm-6 col-12">
                    <div id="text4" class="centered hidden">
                        <h4 id="boothead">Cloud Computing</h4>
                        <p>
                            Cloud computing is the on-demand availability of computer system resources, especially data storage (cloud storage) and computing power,
                            without direct active management by the user. Large clouds often have functions distributed over multiple locations, each location being a data center (Wikipedia).
                        </p>
                    </div>
                    <img src="~/images/Homepage/cloud.jpg" class="img-fluid">
                </div>

                <div id="tech5" class="container col-lg-4 col-md-6 col-sm-6 col-12">
                    <div id="text5" class="centered hidden">
                        <h4 id="boothead">Robotics</h4>
                        <p>
                            Robotics is an interdisciplinary field that integrates computer science and engineering.
                            Robotics involves design, construction, operation, and use of robots. The goal of robotics is to design machines that can help and assist humans (Wikipedia).
                        </p>
                    </div>
                    <img src="~/images/Homepage/robotics.jpg" class="img-fluid">
                </div>

                <div id="tech6" class="container col-lg-4 col-md-6 col-sm-6 col-12">
                    <div id="text6" class="centered hidden">
                        <h4 id="boothead">Blockchain</h4>
                        <p>
                            A blockchain is a growing list of records, called blocks, that are linked together using cryptography.
                            Each block contains a cryptographic hash of the previous block, a timestamp, and transaction data
                            (generally represented as a Merkle tree) (Wikipedia).
                        </p>
                    </div>
                    <img src="~/images/Homepage/blockchain.jpg" class="img-fluid">
                </div>
                <!-- use Javascript/Jquery to add-->
                <!-- good for extension if there are more companies or organisations-->
            </section>

            <section id="bg2" class="col-md-12 col-sm-12 col-12">
                <!--Second back ground image-->
            </section>
        </article>

        <article>
            <!--For search provders-->
            <header hidden="hidden">Six companies and organisations</header> <!-- For search providers-->
            <!--Large Animated Sliders-->
            <div id="myCarousel" class="carousel slide"></div>
        </article>



        <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
            <ul class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
                <li data-target="#myCarousel" data-slide-to="3"></li>
                <li data-target="#myCarousel" data-slide-to="4"></li>
                <li data-target="#myCarousel" data-slide-to="5"></li>
            </ul>

            <!--The slider-->
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="../images/Homepage/ibm.jpg" alt="IBM" class="img-fluid" style="width: 100%;" />
                    <div class="carousel-caption" role="option">
                        <p class="stitle">
                            IBM<br />
                            <a class="btn btn-info" href="https://www.ibm.com/industries/manufacturing">
                                Learn More
                            </a>
                        </p>
                    </div>
                </div>

                <div class="carousel-item">
                    <img src="../images/Homepage/amazon.jpg" alt="Amazon" class="img-fluid" style="width: 100%;" />
                    <div class="carousel-caption" role="option">
                        <p class="stitle">
                            Amazon<br />
                            <a class="btn btn-info" href="https://aws.amazon.com/manufacturing/">
                                Learn More
                            </a>
                        </p>
                    </div>
                </div>

                <div class="carousel-item">
                    <img src="../images/Homepage/microsoft.jpg" alt="Microsoft" class="img-fluid" style="width: 100%;" />
                    <div class="carousel-caption" role="option">
                        <p class="stitle">
                            Microsoft<br />
                            <a class="btn btn-info" href="https://www.microsoft.com/en-us/ai?activetab=pivot1:primaryr6">
                                Learn More
                            </a>
                        </p>
                    </div>
                </div>

                <div class="carousel-item">
                    <img src="~/images/Homepage/google.jpg" alt="Google" class="img-fluid" style="width: 100%;" />
                    <div class="carousel-caption" role="option">
                        <p class="stitle">
                            Google<br />
                            <a class="btn btn-info" href="https://ai.google/">
                                Learn More
                            </a>
                        </p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="../images/Homepage/csiro.jpg" alt="CSIRO" class="img-fluid" style="width: 100%;" />
                    <div class="carousel-caption" role="option">
                        <p class="stitle">
                            CSIRO<br />
                            <a class="btn btn-info" href="https://www.csiro.au/">
                                Learn More
                            </a>
                        </p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="../images/Homepage/department.jpg" alt="Department of Industry, Science, Energy and Resources" class="img-fluid" style="width: 100%;" />
                    <div class="carousel-caption" role="option">
                        <p class="stitle">
                            Department of Industry, Science, Energy and Resources.<br />
                            <a class="btn btn-info" href="https://www.industry.gov.au/">
                                Learn More
                            </a>
                        </p>
                    </div>
                </div>
            </div>

            <!--left Right buttons-->
            <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">

                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>

            <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</body>

Web Dev Assignment 1/Views/Home/Technologies.cshtml

@{
    ViewData["Title"] = "Technologies";
}

<h1>Emerging Technologies</h1>

<div id="elasticGrid"></div>